### ISSUE TITLE
Wont Connect with AC2889/10

### ISSUE THREAD

**Issue by canim60** [iobroker-community-adapters/ioBroker.philips-air#1]
Thx for the Adapter, i would tested with AC2889. is that Coap Compability? I have to Put the Ip, but dont Connected.
 i open the Ip Adress from Puffer, the only feedback ist

`{"error":"Badly formed (DI Comm) request "}`

**Comment by IngoKeutgen** [comment]
Works fine for me .... I just entered the IP whcih I got from my router and it works.
