### ISSUE TITLE
fanSpeed Control throws exception

### ISSUE THREAD

**Issue by derlucas** [iobroker-community-adapters/ioBroker.philips-air#11]
Hey,
when using this adapter with the Jarvis Vis, i get an exception when controlling the fan speed in Level 1 to 3. Mode silent,turbo  are working.

```
philips-air.0 | 2021-05-24 18:49:07.972 | error | Invalid option for fanSpeed: 1. Supported only: {"1":"1","2":"2","3":"3","s":"silent","t":"turbo","a":"auto"}
philips-air.0 | 2021-05-24 18:49:07.971 | error | Error: Invalid option for fanSpeed: 1. Supported only: {"1":"1","2":"2","3":"3","s":"silent","t":"turbo","a":"auto"}     at /opt/iobroker/node_modules/iobroker.philips-air/lib/coap.js:263:31     at Array.forEach (&lt;anonymous&gt;)     at AirPurifier.control (/opt/iobroker/node_modules/iobroker.philips-air/lib/coap.js:256:78)     at Object.stateChange (/opt/iobroker/node_modules/iobroker.philips-air/main.js:64:48)     at Immediate.&lt;anonymous&gt; (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5555:41)     at processImmediate (internal/timers.js:461:21)
philips-air.0 | 2021-05-24 18:49:07.968 | error | uncaught  exception: Invalid option for fanSpeed: 1. Supported only:  {"1":"1","2":"2","3":"3","s":"silent","t":"turbo","a":"auto"}
```

My Datapoint Setting in Jarvis is:
`{"1":"1","2":"2","3":"3","silent":"s","turbo":"t","auto":"a"}`

Am i using it wrong, or is there maybe a check/conversion error?

Second issue: switching to "auto", does not make the device beep and nothing happens. Do i need to set any other attribute too, to get it back to Auto?

Lucas

**Comment by Stefan200583** [comment]
Hi, there are different products of Philips on the market and not all of them understand all commands.

Am 24.05.2021 um 18:59 schrieb Lucas Pleß ***@***.***>:

﻿

Hey,
when using this adapter with the Jarvis Vis, i get an exception when controlling the fan speed in Level 1 to 3. Mode silent,turbo are working.

philips-air.0 | 2021-05-24 18:49:07.972 | error | Invalid option for fanSpeed: 1. Supported only: {"1":"1","2":"2","3":"3","s":"silent","t":"turbo","a":"auto"}
philips-air.0 | 2021-05-24 18:49:07.971 | error | Error: Invalid option for fanSpeed: 1. Supported only: {"1":"1","2":"2","3":"3","s":"silent","t":"turbo","a":"auto"}     at /opt/iobroker/node_modules/iobroker.philips-air/lib/coap.js:263:31     at Array.forEach (&lt;anonymous&gt;)     at AirPurifier.control (/opt/iobroker/node_modules/iobroker.philips-air/lib/coap.js:256:78)     at Object.stateChange (/opt/iobroker/node_modules/iobroker.philips-air/main.js:64:48)     at Immediate.&lt;anonymous&gt; (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5555:41)     at processImmediate (internal/timers.js:461:21)
philips-air.0 | 2021-05-24 18:49:07.968 | error | uncaught  exception: Invalid option for fanSpeed: 1. Supported only:  {"1":"1","2":"2","3":"3","s":"silent","t":"turbo","a":"auto"}


My Datapoint Setting in Jarvis is:
{"1":"1","2":"2","3":"3","silent":"s","turbo":"t","auto":"a"}

Am i using it wrong, or is there maybe a check/conversion error?

Second issue: switching to "auto", does not make the device beep and nothing happens. Do i need to set any other attribute too, to get it back to Auto?

Lucas

**Comment by derlucas** [comment]
Hey!
thanks for your reply. I can however select "Speed 1" and 2 and 3 and any other Option in my "Objects" IOBroker Menu for my philips-air.0->control->fanSpeed. The Devices accepts the settings and the value is green. So my device supports it.

Lucas

**Comment by Apollon77** [comment]
SO it only do not work in Jarvis? WHat exactly is sent?

**Comment by Apollon77** [comment]
New version soon has enhanced debug log

**Comment by Apollon77** [comment]
Please chec GitHub version ...is it working there? WHich device?

**Comment by Apollon77** [comment]
try 0.1.4
