### ISSUE TITLE
Don`t connect with AC1214/10, AC5659/10 and AC2889/10

### ISSUE THREAD

**Issue by Kaschi68** [iobroker-community-adapters/ioBroker.philips-air#2]
Thank you for this adapter. My air purifiers are cloud connected. The IP addresses are known. Unfortunately there is no connection to adapter from AC1214/10, AC5659/10 and AC2889/10.

**Comment by Bias313** [comment]
I can confirm – the adapter does not connect to my AC5659/10.

**Comment by PVMike** [comment]
it is a bit strange, it does not work with my two AC2889/10s either... , but it does work "sometimes" / Somehow
I changed the "alive timeout" and the "reconnect time" from the default values of 30.000 ms to 3.000 ms.. 
then the adapter reads sometimes values.... the adapter changes color from green to yellow regularly

**Comment by Apollon77** [comment]
Can you provide a debug log pelase?

**Comment by Apollon77** [comment]
Ideally Install GitHub version and please post debug log

**Comment by Apollon77** [comment]
Try 0.1.4 ... closing here until more feedback is there
