### ISSUE TITLE
AC2889/10: Hex values in info lines

### ISSUE THREAD

**Issue by neuffer** [iobroker-community-adapters/ioBroker.philips-air#26]
First of all: thank you very much for the Philips Luftreiniger/philips-air adapter!

I just started using it with my new Philips Luftreiniger Series 2000 AC2889/10

Installierte Version: 0.1.4
root@smarthome:/opt/iobroker# iobroker -v
4.0.23
root@smarthome:/opt/iobroker# node -v
v17.9.0

![Screenshot_2022-05-02_20-02-58](https://user-images.githubusercontent.com/16861599/166300649-2a026d28-8c02-4166-97f9-360e46ef4336.png)

In the IOBroker log is see log entries every 30s
philips-air.0	73536	2022-05-02 19:57:41.467	info	Received: 419EC9FE
philips-air.0	73536	2022-05-02 19:57:11.466	info	Received: 0B421D56
philips-air.0	73536	2022-05-02 19:56:41.466	info	Received: 44738F67
philips-air.0	73536	2022-05-02 19:56:10.686	info	Received: 51901F98
philips-air.0	73536	2022-05-02 19:55:40.683	info	Received: 05C9084F

Could someone enlighten me what the hex values in the info lines mean?
Is is any kind of useful information? And if not, can it be suppressed?

Thank you in advance.

**Comment by Apollon77** [comment]
Yes, will be supressed in next version
