### ISSUE TITLE
State value to set for "philips-air.0.device.error" has to be type "string" but received type "number"

### ISSUE THREAD

**Issue by Tscheurgen** [iobroker-community-adapters/ioBroker.philips-air#47]
Hello!
I receive error stated in subject. How should I fix this?
Adapter Version 0.1.7
Thank you!
KR
Jürgen

**Comment by Apollon77** [comment]
Please set the loglevel todebug for the instance ad provide a debug log

**Comment by majadesignz** [comment]
Hallo.
Ich habe den gleichen Fehler und der spammt das Logfile (etwa alle 5s eine Meldung) zu. Wurde das Issue als "fixed" deklariert, weil es keine Rückmeldung mit dem gewünschten Logfile mehr gab oder weil es wirklich gefixed ist (was ich nicht glaube, da ich den Fehler ja noch habe).
Falls ersteres, könnte ich ja ggf. benötigte Debugdaten bereitstellen, da ich daran interessiert bin, dass der Fehler behoben wird.
Grüße

**Comment by majadesignz** [comment]
Vorab anbei schon mal das damals gewünschte Log.
[iobroker.2022-12-15.log.zip](https://github.com/iobroker-community-adapters/ioBroker.philips-air/files/10238967/iobroker.2022-12-15.log.zip)

**Comment by Apollon77** [comment]
Please try GitHub version

**Comment by Apollon77** [comment]
1.0.3
