### ISSUE TITLE
Philips Air purifier loses contact to Philips App

### ISSUE THREAD

**Issue by samakatwist** [iobroker-community-adapters/ioBroker.philips-air#66]
Hey everyone,

my Philips Air purifier 3000i loses contact to the Philips App when connected to this adapter and is shown "offline" in the app; the integration into ioBroker works like a charm, but is there a way to enable the app connection again (so parallel to the ioBroker connection)? Seems like the adapter is capturing the connection rights completely for itself.

Thanks!

**Comment by Apollon77** [comment]
is it Coap or HTTP used? For coap this could be a limitation of the devcie to only communicate locally and only accept one connection ... no idea what we could do against that? Else you would not get any updates in iobroker

**Comment by mcm1957** [comment]
no answer since jan 2023.
Please open a new issue if problem still exists.
